apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: expense
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:    # databases we usually do using statefull sets.
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: suresh/frontend:v1

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: expense
spec:
  type: LoadBalancer    # frontend needs to be exposed to outside world. So service type is LoadBalancer
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
  - name: frontend-port
    port: 80  # this is service port
    protocol: TCP
    targetPort: 80  # this is container port. We can give name also here, but that name to be defined in pod container ports
