apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
# we can use above config map to provide app config variables

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: expense
  labels:
    app: backend
    tier: api
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:    # databases we usually do using statefull sets.
      app: backend
      tier: api
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: api
        project: expense
    spec:
      containers:
      - name: backend
        image: suresh/backend:v1
        envFrom:
        - configMapRef:
            name: backend

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: expense
spec:
  selector:
    app: backend
    tier: api
    project: expense
  ports:
  - name: backend-port
    port: 8080  # this is service port
    protocol: TCP
    targetPort: 8080  # this is container port. We can give name also here, but that name to be defined in pod container ports
