apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers: 
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"] # it runs a command inside container


