apiVersion: v1
kind: Pod
metadata: 
  name: labels-example
  labels:
    project: expense
    module: backend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx

# kubectl describe pod <pod-name> 