apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:      # instead of refering each key from a config map, we can refer entire config map to envronment variables here.
      - configMapRef:
        name: config-map-example



  # env:
  #   # define env variables and get value from config-map
  #   - name: PERSON-NAME
  #     valueFrom:
  #       configMapKeyRef:
  #         name: config-map-example  # name of the configmap
  #         key: person_name   # it gets value from key 'person_name' in the configmap. Finally its PERSON-NAME=suresh
  #   - name: COURSE-NAME
  #     valueFrom:
  #       configMapKeyRef:
  #         name: config-map-example  # name of the configmap
  #         key: course_name  # it gets value from key 'course_name' in the configmap. Finally its COURSE-NAME=k8s        
