apiVersion: v1
kind: Service
metadata:
  name: service-example
spec:
  selector:
    project: expense
    environment: dev
    module: backend
  ports:
  - name: service-port
    port: 80  # this is service port
    protocol: TCP
    targetPort: 80  # this is container port. We can give name also here, but that name to be defined in pod container ports