apiVersion: v1 
kind: Service
metadata:
  name: lb-example
spec:
  type: LoadBalancer
  selector:
    project: expense
    environment: dev
    module: backend
  ports:
  - name: service-port
    port: 80
    targetPort: 80
    protocol: TCP


    