apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: expense
  labels:
    app: mysql
    tier: db
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:    # databases we usually do using statefull sets.
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: suresh/mysql:v1



---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: expense
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-port
    port: 3306  # this is service port
    protocol: TCP
    targetPort: 3306  # this is container port. We can give name also here, but that name to be defined in pod container ports
